include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - bricks/**
    - build/**
    - plugins/**
    - lib/l10n/*.dart
    - '**/*.g.dart'
    - '**/*.mocks.dart'
    - '**/*.config.dart'
    - '**/generated/*.dart'

  errors:
    # TODO: in a recent dart sdk change 
    # a command used in CI `fvm flutter pub publish` 
    # got added with `dart analyze --fatal-infos`
    # and common infos such as deprecated infos
    # are being treated as fatal, breaking our CI.
    # for now we're ignoring these errors
    # but this yaml won't be the recommended one for now.
    # see https://github.com/dart-lang/pub/issues/3870
    deprecated_member_use_from_same_package: ignore
    deprecated_member_use: ignore
    
    missing_required_param: error
    missing_return: error
    prefer_const_constructors: warning


linter:
  rules:
    - lines_longer_than_80_chars
    - directives_ordering
    - require_trailing_commas
    - prefer_final_locals
    - cast_nullable_to_non_nullable
    - null_check_on_nullable_type_parameter
    - prefer_conditional_assignment
    - prefer_if_null_operators
    - prefer_null_aware_method_calls
    - prefer_null_aware_operators
    - unnecessary_null_aware_assignments
    - unnecessary_null_checks
    - unnecessary_null_in_if_null_operators
    - unnecessary_nullable_for_final_variable_declarations
    - use_if_null_to_convert_nulls_to_bools
    - use_test_throws_matchers
    - always_declare_return_types
    - prefer_single_quotes
    - sort_pub_dependencies
    - close_sinks
    - cancel_subscriptions
    - avoid_void_async
    - avoid_returning_null_for_future
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
