name: sorrisinho_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.16+17

environment:
  sdk: '>=2.19.4 <3.0.0'
  flutter: '>=3.7.7'

dependencies:
  amplitude_flutter: ^3.13.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  http: ^0.13.6
  loading_animation_widget: ^1.2.0+4
  package_info_plus: ^4.0.2
  provider: ^6.0.5
  simple_star_rating: ^0.0.3
  shared_preferences: ^2.1.1
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: 'ic_launcher_round'
  ios: false
  image_path: "assets/ic_launcher_round.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  fonts:
    - family: NotoSans
      fonts:
       - asset: fonts/Notosans-Regular.ttf
       - asset: fonts/NotoSans-Bold.ttf
         weight: 700
